#! /usr/bin/env python3
"""filedbutil.

Usage:
    filedbutil refs
    filedbutil list
    filedbutil clean [options]

Options:
    --non-interactive      Do not ask questions.
    --this-is-not-a-drill  Do not just simulate cleanup.
    --help                 Show this page.
"""
from itertools import chain
from json import dumps
from sys import exit as exit_, stderr
from time import sleep

from fancylog import TTYAnimation
from filedb.orm import File
from openimmodb import Anhang
from strflib import Shell
from his.mods.fs.orm import Inode


REFERENCES = (Anhang, Inode)
CLEANUP_QUESTION = 'Type YES if you really want to clean up: '
SIM_TEMPLATE = '{message}{animation}'
SIM_ANIM = ('', '.', '..', '...', ' ..', '  .')
HOT_TEMPLATE = '{animation} {message} {animation}'
HOT_ANIM = ('', Shell.bold(Shell.red('⚠')))


def ask(question, default=False, yes=('yes', 'y'), ignorecase=True):
    """Ask a question and return accordingly."""

    try:
        reply = input(question)
    except EOFError:
        return False

    if not reply:
        return default

    if ignorecase:
        return reply.lower() in (y.lower() for y in yes)

    return reply in yes


def user_abort(*msgs):
    """Indicate abort by user."""

    print()
    print(*msgs, file=stderr)
    return 1


def clean(files, interactive=True, simulate=True):
    """Clean filedb records."""

    for file in File:
        try:
            hardlinks = files[file.id]
        except KeyError:
            print('File <{}> is not used.'.format(file.id))
            question = 'Delete file {}? '.format(file.id)

            if not interactive or ask(question):
                if not simulate:
                    file.remove()

                print('DELETED {} ({}).'.format(file.id, file.sha256sum))
            else:
                print('Keeping {}.'.format(file.id))
        else:
            if file.hardlinks != hardlinks:
                old_hardlinks, file.hardlinks = file.hardlinks, hardlinks

                if not simulate:
                    file.save()

                print('Updated hardlinks of <{}> from {} to {}.'.format(
                    file.id, old_hardlinks, hardlinks))


def make_clean(files, interactive, simulate):
    """Invoke cleaning securely."""

    if simulate:
        animation = TTYAnimation(
            'Just simulating', template=SIM_TEMPLATE, animation=SIM_ANIM)
    else:
        animation = TTYAnimation(
            'THIS IS SERIOUS!', template=HOT_TEMPLATE, animation=HOT_ANIM)

    with animation:
        aborted = False

        try:
            sleep(3)
        except KeyboardInterrupt:
            aborted = True

    if aborted:
        return user_abort('Aborted by user.')

    try:
        if not interactive or ask(
                CLEANUP_QUESTION, yes=('YES',), ignorecase=False):
            clean(files, interactive=interactive, simulate=simulate)
    except KeyboardInterrupt:
        return user_abort('Aborted by user.')


def main(options):
    """Runs the file DB utility."""

    interactive = not options['--non-interactive']
    simulate = not options['--this-is-not-a-drill']
    files = {}

    for record in chain(*REFERENCES):
        try:
            files[record.file] += 1
        except KeyError:
            files[record.file] = 1

    if options['refs']:
        print('Current references:')

        for ref in REFERENCES:
            print(' ' * 3, ref)
    elif options['list']:
        print(dumps(files, indent=2))
    elif options['clean']:
        # Notify user about simulation.
        return make_clean(files, interactive, simulate)

    return 0



if __name__ == '__main__':
    from docopt import docopt
    exit_(main(docopt(__doc__)))
